In [1]:
mySent = 'This book is the best book on Python or M.L. I have ever laid eyes upon.'

In [2]:
import re

In [3]:
mySent

'This book is the best book on Python or M.L. I have ever laid eyes upon.'

In [4]:
regEx = re.compile('\\W*')

In [5]:
listOfTokens = regEx.split(mySent)

In [6]:
listOfTokens

['',
 'T',
 'h',
 'i',
 's',
 '',
 'b',
 'o',
 'o',
 'k',
 '',
 'i',
 's',
 '',
 't',
 'h',
 'e',
 '',
 'b',
 'e',
 's',
 't',
 '',
 'b',
 'o',
 'o',
 'k',
 '',
 'o',
 'n',
 '',
 'P',
 'y',
 't',
 'h',
 'o',
 'n',
 '',
 'o',
 'r',
 '',
 'M',
 '',
 'L',
 '',
 'I',
 '',
 'h',
 'a',
 'v',
 'e',
 '',
 'e',
 'v',
 'e',
 'r',
 '',
 'l',
 'a',
 'i',
 'd',
 '',
 'e',
 'y',
 'e',
 's',
 '',
 'u',
 'p',
 'o',
 'n',
 '',
 '']

In [7]:
regEx = re.compile('\W*')

In [8]:
listOfTokens = regEx.split(mySent)

In [9]:
listOfTokens

['',
 'T',
 'h',
 'i',
 's',
 '',
 'b',
 'o',
 'o',
 'k',
 '',
 'i',
 's',
 '',
 't',
 'h',
 'e',
 '',
 'b',
 'e',
 's',
 't',
 '',
 'b',
 'o',
 'o',
 'k',
 '',
 'o',
 'n',
 '',
 'P',
 'y',
 't',
 'h',
 'o',
 'n',
 '',
 'o',
 'r',
 '',
 'M',
 '',
 'L',
 '',
 'I',
 '',
 'h',
 'a',
 'v',
 'e',
 '',
 'e',
 'v',
 'e',
 'r',
 '',
 'l',
 'a',
 'i',
 'd',
 '',
 'e',
 'y',
 'e',
 's',
 '',
 'u',
 'p',
 'o',
 'n',
 '',
 '']

In [10]:
a = [1,2,3,4,5,6]

In [11]:
import numpy as np 

In [15]:
np.log(a / 2.0)

TypeError: unsupported operand type(s) for /: 'list' and 'float'

In [14]:
a/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [16]:
a/2.0

TypeError: unsupported operand type(s) for /: 'list' and 'float'

In [17]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947])

In [18]:
np.log(a/2)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [19]:
po = np.ones(5)

In [20]:
po

array([1., 1., 1., 1., 1.])

In [21]:
a=[1.2,3.3,4.4,5.5,4.3]

In [22]:
np.log(a/2.0)

TypeError: unsupported operand type(s) for /: 'list' and 'float'

In [23]:
np.log(po/2)

array([-0.69314718, -0.69314718, -0.69314718, -0.69314718, -0.69314718])

In [24]:
np.log(1/2)

-0.6931471805599453